name: Build iOS IPA-Debug

on:
  push:
    branches:
      - master # 只要往 master 提交就自动触发
  workflow_dispatch: # 手动触发构建

jobs:
  ios-build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test execution
        run: echo "Hello GitHub Actions"
